name: WhisperNotch
options:
  bundleIdPrefix: com.whispernotch
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"

targets:
  WhisperNotch:
    type: application
    platform: macOS
    sources:
      - path: WhisperNotch/Sources
    resources:
      - path: WhisperNotch/Assets.xcassets
    dependencies:
      - package: WhisperKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.whispernotch.app
        INFOPLIST_FILE: WhisperNotch/Info.plist
        CODE_SIGN_ENTITLEMENTS: WhisperNotch/WhisperNotch.entitlements
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "WhisperNotch needs access to the microphone for speech-to-text functionality"
        INFOPLIST_KEY_NSAccessibilityUsageDescription: "WhisperNotch needs accessibility access to detect hotkeys and inject text into other applications"
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_IDENTITY: "-"
        OTHER_LDFLAGS:
          - "-framework"
          - AVFoundation
          - "-framework"
          - Accelerate
          - "-framework"
          - Carbon
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          GCC_OPTIMIZATION_LEVEL: "0"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          GCC_OPTIMIZATION_LEVEL: s
          SWIFT_COMPILATION_MODE: wholemodule
